### ISSUE TITLE
Origami install doesnt work with choice "Drupal"

### ISSUE THREAD

**Issue by louis-cuny** [origamiphp/source#385]
When I choose Drupal, it's not creating a .env file and the script throws an error

 [ERROR] Unable to load the environment configuration.
         /Users/louis-cuny/origami/knauf/var/docker//.env

**Comment by ajardin** [comment]
Hello @louis-cuny,

This file should not be used anymore since [v1.8.0](https://github.com/origamiphp/origami/releases/tag/v1.8.0). Could you give me more details about your local environment? I guess you are not using PHP 8.0 which became the minimal requirement starting from [v1.9.0](https://github.com/origamiphp/origami/releases/tag/v1.9.0).

**Comment by louis-cuny** [comment]
You are saying the origami CLI needs php > 8.0 to run correctly ?

**Comment by louis-cuny** [comment]
I have origami 1.5.3, I'm going to upgrade :)



➜  origami origami --verbose
Cannot load Xdebug - it was already loaded

Origami Requirements Checker
============================

 * ✅ docker - A self-sufficient runtime for containers.
 * ✅ docker-compose - Define and run multi-container applications with Docker.
 * ✅ mkcert - A simple zero-config tool to make locally trusted development certificates.

  ___       _                       _
 / _ \ _ __(_) __ _  __ _ _ __ ___ (_)
| | | | '__| |/ _` |/ _` | '_ ` _ \| |
| |_| | |  | | (_| | (_| | | | | | | |
 \___/|_|  |_|\__, |\__,_|_| |_| |_|_|
              |___/

Origami 1.5.3 (env: prod, debug: false)
